[application]
base_url = https://tutorialsninja.com/demo/

[browser]
; chrome | firefox | edge
name = chrome
headless = false
explicit_wait = 15
page_load_timeout = 45

[paths]
login_data = testdata/login_data.csv
search_data = testdata/search_data.csv
screenshots = reports/screenshots
reports = reports
logs = logs
